Спринт 10, выполнено ТЗ, комит №1
LudoEd112/java-filmorate pull request #2
Opened 2024-09-03 21:55 UTC by LudoEd112

2024-09-04 21:15 UTC, sergeymamonov requested changes
Некоторые замечания одинаковые как для фильмов, так и для пользователей.

2024-09-04 21:15 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Long, Film> films = new HashMap<>();
Модификатор доступа.

2024-09-04 21:15 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film == null) {
Если film == null, то в строке выше будет NPE при попытке film.getId() и в эту строку код не дойдет.

2024-09-04 21:15 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
В константы все постоянные значения.

2024-09-04 21:15 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film oldFilm = films.get(film.getId());
А если фильма нет в мапе?

2024-09-04 21:15 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        long currentMaxId = films.keySet()
Это не быстро брать все ключи и искать в них максимальное значение. Можно завести счетчик - будет быстрее работать

2024-09-04 21:15 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ValidateException("Не корректный ввод email");
И пользователь будет гадать, что именно он ввел неправильно. Не очень дружелюбно к пользователю.

2024-09-05 11:29 UTC, LudoEd112 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ValidateException("Поле login не может быть пустым или содержать пробелы");
Не валидный, это означает, что не должно быть пробелов в login. То есть к примеру: IvanovIvan - валидный, а Ivanov Ivan - не валидный

2024-09-05 20:55 UTC, sergeymamonov approved these changes

2024-09-05 20:55 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        User userUpdate = users.get(user.getId());
Аналогично, а если такого пользователя нет в мапе?

2024-09-06 08:02 UTC, merged